; generated by PrusaSlicer 2.0.0+ on 2019-09-01 at 23:43:54

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M107
;----- Start G-coce script
; Manual temp setting. Heat both bed and extruder.
M140 S60                       ; start heating bed
M104 S210 T0    ; start heating extruder
M190 S60                       ; wait for bed temperature
M109 S210 T0   ; wait for extruder temperature

M98 P"0:/macros/before_print"

;M566 X300  Y300 Z100 E3000    ; Set maximum instantaneous speed changes (mm/min) (Jerk)
;M566 X900  Y900 Z100 E3000    ; Set maximum instantaneous speed changes (mm/min) (Jerk)
;M566 X1000  Y1000 Z100 E3000    ; Set maximum instantaneous speed changes (mm/min) (Jerk)
;M566 X1500  Y1500 Z100 E3000    ; Set maximum instantaneous speed changes (mm/min) (Jerk)

;M572 D0 S0.0                                  ; pressure advance
;M572 D0 S0.6                                 ; pressure advance

M566 X600 Y600 Z100 E3000    ; Set maximum instantaneous speed changes (mm/min) (Jerk)
M201 X300 Y300 Z60 E9000     ; max accelleration

; Reset pressure advance for the base.
M572 D0 S0.0                                  ; pressure advance


;----- Start G-coce script end


;M900 K200 ; Filament gcode
G21 ; set units to millimeters
G90 ; use absolute coordinates
;M82 ; use absolute distances for extrusion
M83 ; use relative distances for extrusion
G92 E0


;@@@@@@@@@@@@@

M98 P"/gcodes/_pressure_advance_payload.gcode"

;@@@@@@@@@@@@@

G92 E0
M107
; Filament-specific end gcode
M98 P"0:/macros/after_print"
; filament used [mm] = 701.8
; filament used [cm3] = 1.7
; filament used [g] = 2.1
; filament cost = 0.1
; total filament used [g] = 2.1
; total filament cost = 0.1
; estimated printing time (normal mode) = 17m 47s

; avoid_crossing_perimeters = 0
; bed_shape = 0x0,300x0,300x300,0x300
; bed_temperature = 60
; before_layer_gcode = ;M98 P"0:/macros/camera_click"\n
; between_objects_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 90
; brim_width = 0
; colorprint_heights = 
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; deretract_speed = 0
; disable_fan_first_layers = 1
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = M98 P"0:/macros/after_print"
; extra_loading_move = -2
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = #FFFF0A
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 0.95
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #F77BFF
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "List of materials tested with standard PLA print settings:\n\nDas Filament\nEsun PLA\nEUMAKERS PLA\nFiberlogy HD-PLA\nFillamentum PLA\nFloreon3D\nHatchbox PLA\nPlasty Mladec PLA\nPrimavalue PLA\nProto pasta Matte Fiber\nVerbatim PLA\nVerbatim BVOH"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_soluble = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; first_layer_acceleration = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_speed = 20
; first_layer_temperature = 210
; gcode_comments = 0
; gcode_flavor = reprap
; gcode_label_objects = 0
; high_current_on_filament_swap = 0
; infill_acceleration = 0
; infill_first = 1
; layer_gcode = 
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 90
; max_layer_height = 0
; max_print_height = 280
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 90
; min_layer_height = 0.04
; min_print_speed = 15
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; parking_pos_retraction = 92
; perimeter_acceleration = 0
; post_process = 
; printer_model = 
; printer_notes = PRINTER_HAS_BOWDEN
; remaining_times = 0
; resolution = 0
; retract_before_travel = 0.4
; retract_before_wipe = 10%
; retract_layer_change = 1
; retract_length = 3
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 50
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 3
; skirt_height = 3
; skirts = 4
; slowdown_below_layer_time = 10
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = ";M900 K{if printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}200{elsif nozzle_diameter[0]==0.6}15{else}30{endif} ; Filament gcode"
; start_gcode = ;----- Start G-coce script\n; Manual temp setting. Heat both bed and extruder.\nM140 S[bed_temperature]                       ; start heating bed\nM104 S[first_layer_temperature_0] T0    ; start heating extruder\nM190 S[bed_temperature]                       ; wait for bed temperature\nM109 S[first_layer_temperature_0] T0   ; wait for extruder temperature\n\nM98 P"0:/macros/before_print"\n\n;M566 X300  Y300 Z100 E3000    ; Set maximum instantaneous speed changes (mm/min) (Jerk)\nM566 X900  Y900 Z100 E3000    ; Set maximum instantaneous speed changes (mm/min) (Jerk)\n;M566 X1000  Y1000 Z100 E3000    ; Set maximum instantaneous speed changes (mm/min) (Jerk)\n;M566 X1500  Y1500 Z100 E3000    ; Set maximum instantaneous speed changes (mm/min) (Jerk)\n\nM201 X300 Y300 Z60 E9000        ; max accelleration\n\n;M572 D0 S0.0                                  ; pressure advance\n;M572 D0 S0.6                                 ; pressure advance\nM572 D0 S0.0                                  ; pressure advance\n\n\n;----- Start G-coce script end\n\n\n
; temperature = 200
; threads = 4
; toolchange_gcode = 
; travel_speed = 40
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 0
; wipe = 1
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; z_offset = 0.05
; clip_multipart_objects = 0
; dont_support_bridges = 0
; elefant_foot_compensation = 0.2
; extrusion_width = 0.45
; first_layer_height = 0.2
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 0.2
; raft_layers = 0
; seam_position = rear
; slice_closing_radius = 0.049
; support_material = 0
; support_material_angle = 45
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0.45
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 1
; support_material_interface_spacing = 0
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 0
; support_material_xy_spacing = 0.75
; wipe_into_objects = 0
; xy_size_compensation = 0
; bottom_fill_pattern = rectilinear
; bottom_solid_layers = 3
; bridge_angle = 0
; bridge_flow_ratio = 1
; bridge_speed = 40
; ensure_vertical_shell_thickness = 0
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 60%
; external_perimeters_first = 0
; extra_perimeters = 1
; fill_angle = 90
; fill_density = 10%
; fill_pattern = rectilinear
; gap_fill_speed = 30
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_overlap = 25%
; infill_speed = 50
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 50
; perimeters = 3
; small_perimeter_speed = 50%
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80%
; thin_walls = 1
; top_fill_pattern = rectilinear
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 75%
; top_solid_layers = 3
; wipe_into_infill = 0
; print_settings_id = CoreXY
; filament_settings_id = "My PLA"
; printer_settings_id = CoreXY
; printer_model = 
; printer_variant = 
; default_print_profile = 
; default_filament_profile = ""
; compatible_printers_condition_cummulative = ;"! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; inherits_cummulative = ;"Generic PLA";
