; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Mon Jul 27 2020 16:21:37 GMT-0700 (Pacific Daylight Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


