; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Mon Jul 27 2020 16:21:40 GMT-0700 (Pacific Daylight Time)
; Wait for set temperatures to be reached
M116 P0

