; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Tue Mar 05 2019 22:21:49 GMT-0800 (Pacific Standard Time)

