; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Mon Mar 11 2019 21:01:29 GMT-0700 (Pacific Daylight Time)

