; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Sun Mar 17 2019 11:56:28 GMT-0700 (Pacific Daylight Time)

