; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2 on Tue Mar 05 2019 22:21:50 GMT-0800 (Pacific Standard Time)
; Wait for set temperatures to be reached
M116 P0

