; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2 on Sun Mar 17 2019 11:56:29 GMT-0700 (Pacific Daylight Time)
; Wait for set temperatures to be reached
M116 P0

