; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Mon Jul 27 2020 16:21:38 GMT-0700 (Pacific Daylight Time)
M280 P0 S10 ; deploy BLTouch

